### ISSUE TITLE
Disabling Queue

### ISSUE THREAD

**Issue by tugkan** [u-wave/react-dailymotion#100]
There is a queue feature on dailymotion player which enables/disables to play another video when the current video ends. I couldn't find queue props in the docs. (I want to disable it by the way)

**Comment by goto-bus-stop** [comment]
probably added recently:

|name|type|default||
|-|-|-|-|
| queue-autoplay-next | boolean | true | Whether to play automatically the next item in the queue. |
| queue-enable | boolean | true | Whether to show the Up Next queue. |

i think we should disable these by default.

**Comment by goto-bus-stop** [comment]
:package: `react-dailymotion@0.4.0` disables the Up Next queue by default.
