### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by oyeanuj** [u-wave/react-dailymotion#4]
HI @goto-bus-stop! Thank you for putting out the library! Just wanted to point out that the videos in the demos don't work, so its hard to see the library in action.

Very curious to see how it works!

**Comment by goto-bus-stop** [comment]
:see_no_evil: Whelp! Thanks for the report. I've swapped the videos out for ones used as examples in the Dailymotion API documentation, hopefully these don't get deleted :p

**Comment by oyeanuj** [comment]
Thank you! One other quick question - I don't see a prop to programmatically play or pause the video, which is something that the [API supports](https://developer.dailymotion.com/player#player-api-methods-play)? Is that something you see being added to this library?

**Comment by goto-bus-stop** [comment]
Huh, I thought for sure it had that! Apparently not haha. I just pushed 0.3.0 with a `paused` prop, which is enough for some use cases with autoplay, but it's not perfect (I think it maaay not work well when paused on mount). I hope it works for your case, if I think of something more reliable I'll update 😛On 11 Mar 2017 6:01 pm, Anuj <notifications@github.com> wrote:Thank you! One other quick question - I don't see a prop to programmatically play or pause the video, which is something that the API supports? Is that something you see being added to this library?

**Comment by oyeanuj** [comment]
Thanks for the quick update! One clarification needed though - if one is not `autoPlay` (as it can be annoying sometimes), then do we just `paused` to false and it should start playing?

**Comment by goto-bus-stop** [comment]
Yeah. If you change paused from true to false, it should  start. On 11 Mar 2017 20:39, Anuj <notifications@github.com> wrote:Thanks for the quick update! One clarification needed though - if one is not autoPlay (as it can be annoying sometimes), then do we just paused to false and it should start playing?
